window.esdocSearchIndex = [
  [
    "sim-shim/src/errors.js~parseerror",
    "function/index.html#static-function-ParseError",
    "<span>ParseError</span> <span class=\"search-result-import-path\">sim-shim/src/Errors.js</span>",
    "function"
  ],
  [
    "sim-shim/src/simshim.js~simshim",
    "class/src/SimShim.js~SimShim.html",
    "<span>SimShim</span> <span class=\"search-result-import-path\">sim-shim/src/SimShim.js</span>",
    "class"
  ],
  [
    "sim-shim/src/simshimobj.js~simshimobj",
    "class/src/SimShimObj.js~SimShimObj.html",
    "<span>SimShimObj</span> <span class=\"search-result-import-path\">sim-shim/src/SimShimObj.js</span>",
    "class"
  ],
  [
    "sim-shim/src/simshimplotctx.js~simshimplotctx",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html",
    "<span>SimShimPlotCtx</span> <span class=\"search-result-import-path\">sim-shim/src/SimShimPlotCtx.js</span>",
    "class"
  ],
  [
    "sim-shim/src/simshimsanitize.js~simshimsanitize",
    "class/src/SimShimSanitize.js~SimShimSanitize.html",
    "<span>SimShimSanitize</span> <span class=\"search-result-import-path\">sim-shim/src/SimShimSanitize.js</span>",
    "class"
  ],
  [
    "sim-shim/src/simshimutil.js~simshimutil",
    "class/src/SimShimUtil.js~SimShimUtil.html",
    "<span>SimShimUtil</span> <span class=\"search-result-import-path\">sim-shim/src/SimShimUtil.js</span>",
    "class"
  ],
  [
    "sim-shim/src/utilfunctional.js~add",
    "function/index.html#static-function-add",
    "<span>add</span> <span class=\"search-result-import-path\">sim-shim/src/UtilFunctional.js</span>",
    "function"
  ],
  [
    "sim-shim/src/errors.js~newparseerror",
    "function/index.html#static-function-newParseError",
    "<span>newParseError</span> <span class=\"search-result-import-path\">sim-shim/src/Errors.js</span>",
    "function"
  ],
  [
    "sim-shim/src/utilfunctional.js~push",
    "function/index.html#static-function-push",
    "<span>push</span> <span class=\"search-result-import-path\">sim-shim/src/UtilFunctional.js</span>",
    "function"
  ],
  [
    "sim-shim/src/utilfunctional.js~rest",
    "function/index.html#static-function-rest",
    "<span>rest</span> <span class=\"search-result-import-path\">sim-shim/src/UtilFunctional.js</span>",
    "function"
  ],
  [
    "sim-shim/src/utilfunctional.js~sorted",
    "function/index.html#static-function-sorted",
    "<span>sorted</span> <span class=\"search-result-import-path\">sim-shim/src/UtilFunctional.js</span>",
    "function"
  ],
  [
    "sim-shim/src/utilfunctional.js~zip",
    "function/index.html#static-function-zip",
    "<span>zip</span> <span class=\"search-result-import-path\">sim-shim/src/UtilFunctional.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/errors.js",
    "file/src/Errors.js.html",
    "src/Errors.js",
    "file"
  ],
  [
    "src/rungekutta.js",
    "file/src/RungeKutta.js.html",
    "src/RungeKutta.js",
    "file"
  ],
  [
    "src/simshim.js",
    "file/src/SimShim.js.html",
    "src/SimShim.js",
    "file"
  ],
  [
    "src/simshim.js~simshim#addobject",
    "class/src/SimShim.js~SimShim.html#instance-method-addObject",
    "src/SimShim.js~SimShim#addObject",
    "method"
  ],
  [
    "src/simshim.js~simshim#addplot",
    "class/src/SimShim.js~SimShim.html#instance-method-addPlot",
    "src/SimShim.js~SimShim#addPlot",
    "method"
  ],
  [
    "src/simshim.js~simshim#animate",
    "class/src/SimShim.js~SimShim.html#instance-method-animate",
    "src/SimShim.js~SimShim#animate",
    "method"
  ],
  [
    "src/simshim.js~simshim#constructor",
    "class/src/SimShim.js~SimShim.html#instance-constructor-constructor",
    "src/SimShim.js~SimShim#constructor",
    "method"
  ],
  [
    "src/simshim.js~simshim#getbyid",
    "class/src/SimShim.js~SimShim.html#instance-method-getById",
    "src/SimShim.js~SimShim#getById",
    "method"
  ],
  [
    "src/simshim.js~simshim#getpaused",
    "class/src/SimShim.js~SimShim.html#instance-method-getPaused",
    "src/SimShim.js~SimShim#getPaused",
    "method"
  ],
  [
    "src/simshim.js~simshim#ids",
    "class/src/SimShim.js~SimShim.html#instance-member-ids",
    "src/SimShim.js~SimShim#ids",
    "member"
  ],
  [
    "src/simshim.js~simshim#paused",
    "class/src/SimShim.js~SimShim.html#instance-member-paused",
    "src/SimShim.js~SimShim#paused",
    "member"
  ],
  [
    "src/simshim.js~simshim#plotctx",
    "class/src/SimShim.js~SimShim.html#instance-member-plotCtx",
    "src/SimShim.js~SimShim#plotCtx",
    "member"
  ],
  [
    "src/simshim.js~simshim#removeallobjects",
    "class/src/SimShim.js~SimShim.html#instance-method-removeAllObjects",
    "src/SimShim.js~SimShim#removeAllObjects",
    "method"
  ],
  [
    "src/simshim.js~simshim#removebyid",
    "class/src/SimShim.js~SimShim.html#instance-method-removeById",
    "src/SimShim.js~SimShim#removeById",
    "method"
  ],
  [
    "src/simshim.js~simshim#removeobject",
    "class/src/SimShim.js~SimShim.html#instance-method-removeObject",
    "src/SimShim.js~SimShim#removeObject",
    "method"
  ],
  [
    "src/simshim.js~simshim#retargetcamera",
    "class/src/SimShim.js~SimShim.html#instance-method-retargetCamera",
    "src/SimShim.js~SimShim#retargetCamera",
    "method"
  ],
  [
    "src/simshim.js~simshim#setpaused",
    "class/src/SimShim.js~SimShim.html#instance-method-setPaused",
    "src/SimShim.js~SimShim#setPaused",
    "method"
  ],
  [
    "src/simshim.js~simshim#setsettings",
    "class/src/SimShim.js~SimShim.html#instance-method-setSettings",
    "src/SimShim.js~SimShim#setSettings",
    "method"
  ],
  [
    "src/simshim.js~simshim#start",
    "class/src/SimShim.js~SimShim.html#instance-method-start",
    "src/SimShim.js~SimShim#start",
    "method"
  ],
  [
    "src/simshimobj.js",
    "file/src/SimShimObj.js.html",
    "src/SimShimObj.js",
    "file"
  ],
  [
    "src/simshimobj.js~simshimobj#constructor",
    "class/src/SimShimObj.js~SimShimObj.html#instance-constructor-constructor",
    "src/SimShimObj.js~SimShimObj#constructor",
    "method"
  ],
  [
    "src/simshimobj.js~simshimobj#id",
    "class/src/SimShimObj.js~SimShimObj.html#instance-member-id",
    "src/SimShimObj.js~SimShimObj#id",
    "member"
  ],
  [
    "src/simshimobj.js~simshimobj#manifest",
    "class/src/SimShimObj.js~SimShimObj.html#instance-member-manifest",
    "src/SimShimObj.js~SimShimObj#manifest",
    "member"
  ],
  [
    "src/simshimobj.js~simshimobj#threeobj",
    "class/src/SimShimObj.js~SimShimObj.html#instance-member-threeObj",
    "src/SimShimObj.js~SimShimObj#threeObj",
    "member"
  ],
  [
    "src/simshimobj.js~simshimobj#update",
    "class/src/SimShimObj.js~SimShimObj.html#instance-member-update",
    "src/SimShimObj.js~SimShimObj#update",
    "member"
  ],
  [
    "src/simshimobj.js~simshimobj.fromplotmanifest",
    "class/src/SimShimObj.js~SimShimObj.html#static-method-fromPlotManifest",
    "src/SimShimObj.js~SimShimObj.fromPlotManifest",
    "method"
  ],
  [
    "src/simshimplotctx.js",
    "file/src/SimShimPlotCtx.js.html",
    "src/SimShimPlotCtx.js",
    "file"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#camera",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-camera",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#camera",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#constructor",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-constructor-constructor",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#constructor",
    "method"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#controls",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-controls",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#controls",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#light",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-light",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#light",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#metrics",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-metrics",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#metrics",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#objects",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-objects",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#objects",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#render",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-method-render",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#render",
    "method"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#renderer",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-renderer",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#renderer",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#scene",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-member-scene",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#scene",
    "member"
  ],
  [
    "src/simshimplotctx.js~simshimplotctx#updatemetrics",
    "class/src/SimShimPlotCtx.js~SimShimPlotCtx.html#instance-method-updateMetrics",
    "src/SimShimPlotCtx.js~SimShimPlotCtx#updateMetrics",
    "method"
  ],
  [
    "src/simshimsanitize.js",
    "file/src/SimShimSanitize.js.html",
    "src/SimShimSanitize.js",
    "file"
  ],
  [
    "src/simshimsanitize.js~simshimsanitize.checkplotobj",
    "class/src/SimShimSanitize.js~SimShimSanitize.html#static-method-checkPlotObj",
    "src/SimShimSanitize.js~SimShimSanitize.checkPlotObj",
    "method"
  ],
  [
    "src/simshimsanitize.js~simshimsanitize.checksettings",
    "class/src/SimShimSanitize.js~SimShimSanitize.html#static-method-checkSettings",
    "src/SimShimSanitize.js~SimShimSanitize.checkSettings",
    "method"
  ],
  [
    "src/simshimutil.js",
    "file/src/SimShimUtil.js.html",
    "src/SimShimUtil.js",
    "file"
  ],
  [
    "src/simshimutil.js~simshimutil.makesurfacegeometry",
    "class/src/SimShimUtil.js~SimShimUtil.html#static-method-makeSurfaceGeometry",
    "src/SimShimUtil.js~SimShimUtil.makeSurfaceGeometry",
    "method"
  ],
  [
    "src/simshimutil.js~simshimutil.toquat",
    "class/src/SimShimUtil.js~SimShimUtil.html#static-method-toQuat",
    "src/SimShimUtil.js~SimShimUtil.toQuat",
    "method"
  ],
  [
    "src/simshimutil.js~simshimutil.tovec3",
    "class/src/SimShimUtil.js~SimShimUtil.html#static-method-toVec3",
    "src/SimShimUtil.js~SimShimUtil.toVec3",
    "method"
  ],
  [
    "src/simshimutil.js~simshimutil.uniquesymbolnames",
    "class/src/SimShimUtil.js~SimShimUtil.html#static-method-uniqueSymbolNames",
    "src/SimShimUtil.js~SimShimUtil.uniqueSymbolNames",
    "method"
  ],
  [
    "src/utilfunctional.js",
    "file/src/UtilFunctional.js.html",
    "src/UtilFunctional.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ]
]